logging:
  level:
    com:
      example:
        resilence4j:
          openfeign: DEBUG

spring:
  cloud:
    openfeign:
      #      circuitbreaker:
      #        enabled: true
      alphanumeric-ids:
        enabled: true
      httpclient:
        enabled: true
        connection-timeout: 5000
        max-connections: 200
      config:
        log-client:
          loggerLevel: FULL

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true # actuator ?? ??? ?? ??
      failureRateThreshold: 80 # ??? ??? ?? ???(???)?? ? ?? ???? ??? ???.
      waitDurationInOpenState: 1m # ?? ??? ???? ??, ?? ???? ??? ??? ????.
      slidingWindowType: COUNT_BASED
      #      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 10
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
#      recordExceptions:
#        - java.net.UnknownHostException
#        - org.springframework.web.client.HttpServerErrorException
#        - java.util.concurrent.TimeoutException
#        - java.io.IOException
      ignoreExceptions:
        - com.example.resilence4j.config.BusinessException
  #    shared:
  #      slidingWindowSize: 100
  #      permittedNumberOfCallsInHalfOpenState: 30
  #      waitDurationInOpenState: 1s
  #      failureRateThreshold: 50
  #      eventConsumerBufferSize: 10
  #      ignoreExceptions:
  #        - com.example.resilence4j.config.BusinessException
  instances:
    backendA:
      baseConfig: default
#    backendB:
#      registerHealthIndicator: true
#      slidingWindowSize: 10
#      minimumNumberOfCalls: 10
#      permittedNumberOfCallsInHalfOpenState: 3
#      waitDurationInOpenState: 5s
#      failureRateThreshold: 50
#      eventConsumerBufferSize: 10
#      recordFailurePredicate: com.example.resilence4j.config.RecordFailurePredicate

management:
  endpoints:
    web:
      exposure:
        include:
          - "*" #??????actuator????

  health:
    circuitbreakers:
      enabled: true # circuitbreakers ?? ??